### ISSUE TITLE
Edit Pickle files

### ISSUE THREAD

**Issue by Joseph11024** [projectpokemon/PoGoEncTool#4]
Hey how's it going? There is no issue I was just trying to get in touch with you but this is the only way I can seem to find on GitHub.

Anyways i hope you dont mind....I am trying to figure out how to read and edit pickle files. Ie tried doing some things on my own but cant seem to find any reliable source explaining how to do it or what i need. I have seen you submit a few of these files on pkhex so i figured i would reach out and see if you would be willing to help me out or point me in the right direction. Any help or information would be greatlyappreciated.

**Comment by sora10pls** [comment]
`.pkl` formatted files are not one-size-fits-all, they're just serialized data with a number of varying formats.
In this case, PoGoEncTool serializes a pickle in the following way:
https://github.com/projectpokemon/PoGoEncTool/blob/5661cde094604b75ed24f9983cf18b1177371d2c/PoGoEncTool.Core/Util/PogoPickler.cs#L43-L51

This is better suited for a [PKHeX discussion](https://github.com/kwsch/PKHeX/discussions), if anything. Although, I don't see a use case in needing to serialize data for PKHeX considering everything it would need is already accounted for, such as wild encounters and Mystery Gift data. You can read up on the PKHeX API to learn how PKHeX reads pickles for specific formats.

Please keep any future issues pertinent to the PGET database, thank you!
